name: Ubuntu Desktop (Google Remote Desktop)
on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter Google Remote Desktop (Debian Linux) code'
        required: true
      computername:
        description: 'Computer Name'
        default: 'ZVM'
        required: true
      pincode:
        description: 'Six digit Pin'
        default: '12345678'
        required: true
      desktop:
        description: 'desktop number/code'
        default: 'ubuntu'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Mask Code & Pin.
      shell: bash
      run: |
        _Code=$(jq -r '.inputs.authcode' $GITHUB_EVENT_PATH)
        _CName=$(jq -r '.inputs.computername' $GITHUB_EVENT_PATH)
        _Pin=$(jq -r '.inputs.pincode' $GITHUB_EVENT_PATH)
        echo ::add-mask::$_Code
        echo ::add-mask::$_CName
        echo ::add-mask::$_Pin
        echo AuthCode="$_Code" >> $GITHUB_ENV
        echo ComputerName="$_CName" >> $GITHUB_ENV
        echo AuthPin="$_Pin" >> $GITHUB_ENV
    - name: Setup Ubuntu Desktop Environment.
      if: github.event.inputs.desktop == 'ubuntu' || github.event.inputs.desktop == '1'
      run: |
        sudo apt update 
        sudo apt install ubuntu-desktop
    - name: Setup UKUI Desktop Environment.
      if: github.event.inputs.desktop == 'ukui' || github.event.inputs.desktop == '2'
      run: |
        sudo apt update
        sudo add-apt-repository ppa:ubuntukylin-members/ukui -y
        sudo apt install ukui-desktop-environment
    - name: Setup LXDE Desktop Environment.
      if: github.event.inputs.desktop == 'lxde' || github.event.inputs.desktop == '3'
      run: |
        sudo apt update
        sudo apt install lxqt sddm -y
    - name: Setup Mate Desktop Environment.
      if: github.event.inputs.desktop == 'mate' || github.event.inputs.desktop == '4'
      run: |
        sudo apt update
        sudo apt install ubuntu-mate-desktop -y
    - name: Setup Budgie Desktop Environment.
      if: github.event.inputs.desktop == 'budgie' || github.event.inputs.desktop == '5'
      run: |
        sudo apt update
        sudo apt install ubuntu-budgie-desktop -y
    - name: Setup KDE Plasma Desktop Environment.
      if: github.event.inputs.desktop == 'kdeplasma' || github.event.inputs.desktop == '6'
      run: |
        sudo apt update
        sudo apt install tasksel
        sudo tasksel install kubuntu-desktop
    - name: Setup Deepin Desktop Environment.
      if: github.event.inputs.desktop == 'deepin' || github.event.inputs.desktop == '7'
      run: |
        sudo apt update
        sudo add-apt-repository ppa:ubuntudde-dev/stable -y
        sudo apt install ubuntudde-dde
    - name: Setup XFCE Desktop Environment.
      if: github.event.inputs.desktop == 'xfce' || github.event.inputs.desktop == '8'
      run: |
        sudo apt update
        sudo apt install xfce4
        sudo chmod 777 /home/runneradmin/
        sudo bash -c 'echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'
    - name: Setup Cinnamon Desktop Environment.
      if: github.event.inputs.desktop == 'cinnamon' || github.event.inputs.desktop == '9'
      run: |
        sudo apt update
        sudo apt install cinnamon-desktop-environment
    - name: Setup Google Remote Desktop.
      run: |
        sudo apt install nautilus expect nano -y
        sudo apt install --assume-yes xscreensaver
        sudo apt-get update
        sudo apt-get install xbase-clients python3-psutil xvfb -y
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        wget https://raw.githubusercontent.com/mrijoo/RDP/main/Files/t.bat
        sudo dpkg --install chrome-remote-desktop_current_amd64.deb
        sudo apt install --assume-yes --fix-broken
        sudo hostname ${{ env.ComputerName }}
        touch setup.sh
        echo "${{ env.AuthCode }}" >> "setup.sh"
        chmod 777 setup.sh
    - name: Starting Google Remote Desktop
      run: |
        expect -c '
        spawn ./setup.sh
        expect "Enter a PIN of at least six digits: "
        send "${{ env.AuthPin }}\r"
        expect "Enter the same PIN again: "
        send "${{ env.AuthPin }}\r"
        expect eof
        '
    - name: Keep Alive.
      shell: bash
      run: sh t.bat