name: Google Remote Desktop

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter Google Remote Desktop ( Windows (PowerShell) ) code'
        required: true
      pincode:
        description: 'Six digit Pin'
        default: '12345678'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./Files/GRD-Setup.ps1
    - name: Starting Google Remote Desktop
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: ./Files/t.bat
